### ISSUE TITLE
NuGet package for BasicAuthentification

### ISSUE THREAD

**Issue by zoranpro** [Kukkimonsuta/Odachi#1]
Hi @Kukkimonsuta,

I was wondering if you could place this code on NuGet?

**Comment by Kukkimonsuta** [comment]
I was considering it, but things are still too unstable. I think I'll wait for a bit, for now I recommend using git subtree and include it in your project, since it's likely you'll have to make some modifications to the library sooner or later.

**Comment by herecydev** [comment]
Any chance this can get nuget'd. We're in RC1 now and I see you've updated to reflect this. Things should be considerably more stable now.

**Comment by Kukkimonsuta** [comment]
Sure, I'll try to get to it within the next few days.

**Comment by Kukkimonsuta** [comment]
Sorry for the delay, nuget packages should be ready now:

https://www.nuget.org/packages/Odachi.Security.BasicAuthentication
