### ISSUE TITLE
Upgrade to ASP.NET Core 2.0

### ISSUE THREAD

**Issue by sjurmr** [Kukkimonsuta/Odachi#10]
Any plans on upgrading to ASP.NET Core 2.0?

**Comment by Kukkimonsuta** [comment]
Yes, most likely during september. If you need it sooner, let me know and I'll see what I can do.

**Comment by sjurmr** [comment]
Great. I'm not in production yet so I'll wait at 1.x until you get there. Thanks for you good work!

**Comment by RehanSaeed** [comment]
2.0 is out, would appreciate an upgrade.

**Comment by RehanSaeed** [comment]
BTW, I just need the basic auth package, nothing else.

**Comment by Kukkimonsuta** [comment]
On the CI feed ( https://ci.appveyor.com/nuget/odachi ) there is now `Odachi.AspNetCore.Authentication.Basic` with version `2.0.0-preview-000143` targetting `netstandard2.0` and `ASP.NET Core 2.0`. Other packages are currently without change. I'll try to finish the rest during september and then I'll put everything on nuget.

Please note that the authentication has changed quite a bit. For more info read https://github.com/aspnet/Announcements/issues/262

**Comment by RehanSaeed** [comment]
Any plans to get that package onto NuGet? Even as a preview.

**Comment by Kukkimonsuta** [comment]
Released preview on NuGet as version `2.0.0-preview-000148`. It might take some time before it gets indexed. Please note that I have not yet used it in production anywhere as we are staying on 1.x for a bit longer. Let me know if you find any issues, thank you.

**Comment by RehanSaeed** [comment]
Have given it a test and seems to mostly work. However, it no longer picks up configuration from my `appsettings.json`. I register my `BasicOptions` object in configuration like so:

```
services.Configure<BasicOptions>(configuration.GetSection("BasicAuthentication"));
```

Looks like `IOptions` has changed a lot too. I now have to add this:

```
public class OptionsWrapperMonitor<T> : IOptionsMonitor<T>
{
    public OptionsWrapperMonitor(T currentValue) =>
        this.CurrentValue = currentValue;

    public T CurrentValue { get; }

    public T Get(string name) => this.CurrentValue;

    public IDisposable OnChange(Action<T, string> listener) => null;
}

services.AddSingleton<IOptionsMonitor<BasicOptions>>(
    x => new OptionsWrapperMonitor<BasicOptions>(x.GetRequiredService<IOptions<BasicOptions>>().Value))
```

See https://github.com/aspnet/Options/issues/200 for more info. I'm sure there must be a simpler way.

**Comment by Kukkimonsuta** [comment]
You don't need to create `OptionsWrapperMonitor`, you just need to name the options instance with the scheme name:

https://github.com/aspnet/Security/blob/a81465d5a98bff94e1e0c08814b5d9d60da644ab/src/Microsoft.AspNetCore.Authentication/AuthenticationHandler.cs#L89

I have updated the sample project. If you don't use custom scheme name, you should use

```cs
services.Configure<BasicOptions>(BasicDefaults.AuthenticationScheme, configuration.GetSection("BasicAuthentication"));
```

**Comment by RehanSaeed** [comment]
Have you tried this using .NET 4.6.1 instead of netstandard? It's throwing a NullReferenceException when calling the ClaimsIdentity constructor for me.

**Comment by Kukkimonsuta** [comment]
I've just tried included sample while targetting `net461` and it seem to work fine. Could you try making simple repro (create new empty project and reproduce the issue with minimal steps)?
