### ISSUE TITLE
Previous version allowed access to the request...

### ISSUE THREAD

**Issue by ShiftySituation** [Kukkimonsuta/Odachi#12]
The previous version allowed access to the request.  I need it as I'm pulling keys from the request path... something like: 

`
builder.UseWhen(context => context.Request.Path.StartsWithSegments(new PathString("/api/v1")), b => b.UseBasicAuthentication(options =>
            {
options.Events = new BasicEvents
                {
                    OnSignIn = async context =>
                    {
                            string someKeyFromTheRequestUrl = context.Request.Path.Value.Split('/').Skip(4).FirstOrDefault();
        }
                };
            }));
}
`

`OnSignIn` func is the concern.

**Comment by Kukkimonsuta** [comment]
This did not change, `Request` is still available in event context, however there is no longer a `UseBasicAuthentnication`. You need to adapt it to the asp.net core 2.0 authentication scheme. See sample on how to use multiple schemes: https://github.com/Kukkimonsuta/Odachi/blob/master/samples/BasicAuthenticationSample/Startup.cs

**Comment by ShiftySituation** [comment]
@Kukkimonsuta You are correct.  I didn't realize I wasn't on version 2 (forgot to include prereleases when updating my nuget packages).   I have it working correctly but one thing I can't figure out is, how to I get the request to pass to the controller?

**Comment by Kukkimonsuta** [comment]
https://github.com/Kukkimonsuta/Odachi/blob/e5d3608fa0cad9408088dbc2c63c10931b059741/samples/BasicAuthenticationSample/Startup.cs#L56-L58

These lines mark the request as authenticated, if that's what you mean. If not, please try building small project I could use to reproduce what you are trying to do and upload it here, so I can help you better.

**Comment by ShiftySituation** [comment]
I was using `.MapWhen` but once I changed it to `.UseWhen` it works with 

`
builder.Use(async (context, next) =>
{
                var result = await context.AuthenticateAsync(basicScheme);
                context.User = result != null && result.Succeeded ? context.User = result.Principal : new ClaimsPrincipal(new ClaimsIdentity());
                if (!context.User.Identity.IsAuthenticated)
                {
                    await context.ChallengeAsync(basicScheme);
                }
                else
                {
                    await next();
                }
            });
`

Thanks for your help @Kukkimonsuta
