### ISSUE TITLE
Why is the package in "preview"?

### ISSUE THREAD

**Issue by fatmanmclone90** [Kukkimonsuta/Odachi#15]
I've been using this package in a dotnet 2.2 application for a while now, I want to update to dotnet 3.1 but I cannot depend on the package as its still in "preview".

I see no open issues, what needs to happen for it to go to release?  The 3.1 SDK no longer lets you reference preview dependencies by using "NoWarn NU5104" in the proj file.

Be great to see this package go to release, I've relied on it for a while no without issues.

**Comment by Kukkimonsuta** [comment]
There isn't any reason, we've just kind of been using it right from CI and assumed we're the only one using this so didn't bother :)

I have pushed the release button and if all goes well it should pop up as v3.1.0 with 3.1.x dependencies on nuget soon.

Out of curiosity, which part of the suite are you using?

**Comment by fatmanmclone90** [comment]
Perfect thank you very much.  I find it a neat solution to add Basic Auth to my APIS, we use the Odachi.AspNetCore.Authentication.Basic project.
