### ISSUE TITLE
`AuthenticationHandler` interface has changed in beta6

### ISSUE THREAD

**Issue by friism** [Kukkimonsuta/Odachi#3]
There are some changes in the latest `beta6` Security release that has braking changes to the API.

**Comment by Kukkimonsuta** [comment]
Thanks for reporting it, I've made the necessary modifications. I've also reworked the authentication to be more alike the rest of the auth methods by removing `IAuthenticator` and using notifications instead.

**Comment by friism** [comment]
Epic, thank you so much!
