### ISSUE TITLE
Cannot build with Stable Beta 8

### ISSUE THREAD

**Issue by matthiasjost** [Kukkimonsuta/Odachi#4]
I cannot build the project with the stable beta 8 build:

Error CS0117
'ConfigureOptions<BasicAuthenticationOptions>' does not contain a definition for 'Name' 
Odachi.Security.BasicAuthentication.DNX 4.6

Error CS1061  
'StringValues' does not contain a definition for 'StartsWith' and no extension method 'StartsWith' accepting a first argument of type 'StringValues' could be found (are you missing a using directive or an assembly reference?)  
Odachi.Security.BasicAuthentication.DNX 4.6

Error CS1061  
'StringValues' does not contain a definition for 'Substring' and no extension method 'Substring' accepting a first argument of type 'StringValues' could be found (are you missing a using directive or an assembly reference?) 
Odachi.Security.BasicAuthentication.DNX 4.6

Error CS1729  
'AuthenticationMiddleware<BasicAuthenticationOptions>' does not contain a constructor that takes 5 arguments  
Odachi.Security.BasicAuthentication.DNX 4.6

Error CS0117  
'ConfigureOptions<BasicAuthenticationOptions>' does not contain a definition for 'Name' 
Odachi.Security.BasicAuthentication.DNX Core 5.0

Error CS1061    'StringValues' does not contain a definition for 'StartsWith' and no extension method 'StartsWith' accepting a first argument of type 'StringValues' could be found (are you missing a using directive or an assembly reference?)
Odachi.Security.BasicAuthentication.DNX Core 5.0

Error CS1061    'StringValues' does not contain a definition for 'Substring' and no extension method 'Substring' accepting a first argument of type 'StringValues' could be found (are you missing a using directive or an assembly reference?) 
Odachi.Security.BasicAuthentication.DNX Core 5.0

Error CS1729    'AuthenticationMiddleware<BasicAuthenticationOptions>' does not contain a constructor that takes 5 arguments  
Odachi.Security.BasicAuthentication.DNX Core 5.0

Error CS1061 'IApplicationBuilder' does not contain a definition for 'UseErrorPage' and no extension method 'UseErrorPage' accepting a first argument of type 'IApplicationBuilder' could be found (are you missing a using directive or an assembly reference?)  
BasicAuthenticationSample.DNX 4.6

Error CS1061    'IApplicationBuilder' does not contain a definition for 'UseErrorPage' and no extension method 'UseErrorPage' accepting a first argument of type 'IApplicationBuilder' could be found (are you missing a using directive or an assembly reference?) 
BasicAuthenticationSample.DNX Core 5.0

**Comment by Kukkimonsuta** [comment]
Upgraded to beta8. Changes:
- use of the new hosting model in IIS (`Microsoft.AspNet.IISPlatformHandler`)
- renamed basic authentication `Notifications` to `Events`
- adapted to more changes in final beta8 in sample project (`UseErrorPage` => `UseDeveloperExceptionPage` etc.)

**Comment by matthiasjost** [comment]
Wow thank you that was pretty fast.

**Comment by matthiasjost** [comment]
I could built it successfully. I am trying to run the "BasicAuthentication Sample".  I received "HTTP Error 500.19 - Internal Server Error" What am I doing wrong?

**Comment by Kukkimonsuta** [comment]
Do you have beta8 tools installed (not just dnvm)?

http://www.microsoft.com/en-us/download/details.aspx?id=49442

WebToolsExtensionsVS14.msi - if you are using full Visual Studio
WebToolsExtensionsVWD14.msi - if you are using Visual Studio Express

**Comment by matthiasjost** [comment]
I will try that, no! I installed once the web tools of an earlier version but not this time. Will try that immediately. Thank you.

**Comment by Kukkimonsuta** [comment]
No problem, it should fix your problem by installing "Http Platform Handler" to IIS, which is the new way how ASP.NET 5 is hosted in IIS. Let me know how it goes :)

**Comment by matthiasjost** [comment]
OK. Basically what I am trying to do is write our own Authentication Middleware based on another library supporting JWT tokens  (https://github.com/dvsekhvalnov/jose-jwt) and your example here. So I will use this example you are provding as a starting point. But it seems not that simple. But I will try after installing the Webtools and when it runs.

**Comment by matthiasjost** [comment]
After installation it runs and builds correct!
