### ISSUE TITLE
Hide away logic

### ISSUE THREAD

**Issue by herecydev** [Kukkimonsuta/Odachi#5]
Keeping the startup as clean as possible is the best approach. I think it would be good to cleanup [this logic](https://github.com/Kukkimonsuta/Odachi/blob/master/samples/BasicAuthenticationSample/Startup.cs#L28). The username and password can be configurable through the options and the Func used as the default instead of [this](https://github.com/Kukkimonsuta/Odachi/blob/master/src/Odachi.Security.BasicAuthentication/Events/BasicEvents.cs#L23).

This would look something like this:

``` c#
app.UseBasicAuthentication(options =>
{
options.Realm = "Odaci"
options.Username = "User"
options.Password = "Password"
}
```

**Comment by Kukkimonsuta** [comment]
I agree that there could be more simple way, but I really dislike specifying `username` and `password` directly in options like this. There also need to be an option to add claims to the principal. I'm thinking of something more like this:

```
app.UseBasicAuthentication(options =>
{
    options.Credentials.Add("admin", "1234", new Claim(ClaimTypes.Name, "administrator"));
});
```

This would at least allow having more than one user, while more complex interaction would have to be done through events. What do you think?

**Comment by herecydev** [comment]
Based on a typical basic auth scenario (which is supposed to be pretty simple; server <-> server or 1 key fits all). I would probably go with an IOptions<BasicAuthenticationOptions> to be injected in. It can accept either the authentication key as a whole or Username + password. I'm not a fan of inlining the config as you don't gain the benefits of using the IOptions and it's definitely the cleanest option. You would end up with:

``` c#
app.UseBasicAuthentication(); //would expect an IOptions to be bound in the ConfigureServices() and can inject middleware into the pipeline.
```

But there may be other scenarios you need to cater for that I'm not thinking about.

**Comment by herecydev** [comment]
Thanks for releasing as a nuget :+1: . Did you have any more thoughts towards this?

**Comment by Kukkimonsuta** [comment]
No problem. I've worked on this for a bit, but I'm struggling a little with `IOptions` and how to do this properly. I still intend to allow specifying multiple credentials, but it will be configurable through config file. Current prototype is:

```
    "BasicAuthentication": {
        "Realm": "Simple",
        "Credentials": [
            {
                "Username": "user1",
                "Password": "password",
                "Claims": [
                    { "Type": "foo", "Value": "bar" }
                ]
            },
            { "Username": "user2", "Password": "cookies" }
        ]
    }
```

**Comment by herecydev** [comment]
What about:

``` c#
    public sealed class BasicAuthenticationOptions
    {
        public string Realm { get; set; }
        public IEnumerable<Credential> Credentials { get; set; }
    }

    public sealed class Credential
    {
        public string Username { get; set; }
        public string Password { get; set; }
        public IEnumerable<Claim> Claims { get; set; }
    }
```

Nice and simple from your perspective. It requires the user to do a little effort but gives them plenty of flexibility and massively cleans up the code we were talking about.

The user can use whichever [configuration](https://github.com/aspnet/Configuration) model they wish; and can bind this all up before calling `services.AddBasicAuthentication()`. I believe this is the most common approach to aspnet 5 middleware.

**Comment by Kukkimonsuta** [comment]
Yeah that's pretty much what I'm going for, the example was just how it would look in json, but user is able to choose whatever way to configure it. Hopefully I'll have some time during the next few days to finish it.

The thing I was struggling with was on how exactly does the configuration process work. Does the middleware attempt to resolve `IOptions<BasicOptions>` when no parameters are given?

**Comment by herecydev** [comment]
The [AuthenticationMiddleware](https://github.com/aspnet/Security/blob/dev/src/Microsoft.AspNet.Authentication/AuthenticationMiddleware.cs) is a more unique scenario. Typically I would expect the following:

``` c#
services.Configure<MyOptions>(options => //configure...);
```

And in the dependant class

``` c#
public class Consumer : IConsumer
{
    public Consumer(IOptions<MyOptions> options)
    {
        //Do something
    }
}
```

Then [DependencyInjection](https://github.com/aspnet/DependencyInjection) will do all the magic for you.

I think it's best to follow suit with the other providers in this case. [Here's an example](https://github.com/aspnet/Security/blob/dev/src/Microsoft.AspNet.Authentication.Cookies/CookieAppBuilderExtensions.cs#L68) of how the cookie auth works.

**Comment by Kukkimonsuta** [comment]
I've updated the configuration, but you still have to retrieve the options from DI and pass it into `UseBasicAuthentication(options)` (see: [Startup.cs:41](https://github.com/Kukkimonsuta/Odachi/blob/master/samples/BasicAuthenticationSample/Startup.cs#L41)), so you can't just call `app.UseBasicAuthentication();`, but the behavior seem to be the same with cookie authentication. Could you please check whether that makes sense before I push the new version to nuget?

**Comment by Kukkimonsuta** [comment]
Oh by the way, the latest (but sometimes possibly broken) version can be found at nuget feed https://ci.appveyor.com/nuget/odachi

**Comment by herecydev** [comment]
It's looking lots better. One change I would make that could make it `app.UseBasicAuthentication();` would be:

``` c#
public static IApplicationBuilder UseBasicAuthentication(this IApplicationBuilder app)
        {
            if (app == null)
                throw new ArgumentNullException(nameof(app));

            var options = app.ApplicationServices.GetService<IOptions<BasicOptions>>();

            return app.UseBasicAuthentication(options ?? new BasicOptions());
        }
```

This makes it so it'll try and get the options if you've bound it, if not provide a blank one for you. You then have some more overloads to pass in as well. Choices for everyone :)

**Comment by Kukkimonsuta** [comment]
This does sound like a good idea and it was my initial thought, but unless I'm missing something none of the default authentication middlewares do this :/ I like this design though, so I'll put it in for now and see if there is a valid reason why it shouldn't be there.

**Comment by herecydev** [comment]
Awesome, will your CI build automatically push that to nuget?

**Comment by Kukkimonsuta** [comment]
Yep, every commit from "preview" branch (and eventually "stable" branch) should go to nuget though CI. It should be done in a few minutes.
