### ISSUE TITLE
Split AspNet and non-AspNet projects

### ISSUE THREAD

**Issue by Kukkimonsuta** [Kukkimonsuta/Odachi#6]
Since the scope of this solution will expand soon(ish) to more areas we've decided to change the namespaces to reflect whether given project is supposed to be used within `AspNet` or everywhere. This structure will also more closely reflect the structure used by https://github.com/aspnet .

Breaking changes:
`Odachi.Security.BasicAuthentication` => `Odachi.AspNet.Authentication.Basic`
`Odachi.MvcPages` => `Odachi.AspNet.MvcPages`

Current nuget packages `Odachi.Security.BasicAuthentication` and `Odachi.MvcPages` were unlisted and will be no longer updated. New packages are available:

https://www.nuget.org/packages/Odachi.AspNet.Authentication.Basic/
https://www.nuget.org/packages/Odachi.AspNet.MvcPages/

@herecydev @MatthiasJost @friism @zoranpro

**Comment by herecydev** [comment]
Yep that seems logical to me.

**Comment by matthiasjost** [comment]
We gave up BasicAuthentication and implemented JSON Web Tokens, but thank you for the notification. I think such project like yours are very valuable, not only, but also for learning purposes.
