### ISSUE TITLE
BasicAuthenticationSample & AspNet.Identity

### ISSUE THREAD

**Issue by Kabanets** [Kukkimonsuta/Odachi#7]
How configure BasicAuthenticationSample  for one MVC controller? Another controllers must use AspNet.Identity.

**Comment by Kukkimonsuta** [comment]
You should be able to do this by decorating the controller with `[Authorize(ActiveAuthenticationSchemes = "Basic")]` and disabling `AutomaticChallenge` in `BasicOptions`. Let me know how it goes.

**Comment by Kabanets** [comment]
Excellent! Thank you.
