### ISSUE TITLE
ASP.NET Core 1.0 Support?

### ISSUE THREAD

**Issue by RehanSaeed** [Kukkimonsuta/Odachi#8]
The endless upgrades are finally coming to a close with ASP.NET Core. This upgrade is fairly trivial and the only files you are likely needing to change are global.json and project.json.

**Comment by Kukkimonsuta** [comment]
I've got some other stuff that needs my attention right now, but I'll get to this by the end of the day.

**Comment by RehanSaeed** [comment]
Cool!

**Comment by Kukkimonsuta** [comment]
Updated and pushed to nuget as `1.0.0`. Let me know if you have any problems.
